import type {Metadata} from 'next';
import {Geist, Geist_Mono, Inter} from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Apply font classNames directly to the html tag
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${inter.variable}`}>
      {/* Keep suppressHydrationWarning for now, might be removable later */}
      <body suppressHydrationWarning={true}>
        {/* Remove font variables from here, apply antialiased */}
        <div className="antialiased">{children}</div>
      </body>
    </html>
  );
}
